server:
  port: 10011

canal-kudu-syncer:
  zk:
    servers: test01:2181
  canal:
    destination: i2
  kudu:
    masterAddresses: test02


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver