server:
  port: 10011

canal-kudu-syncer:
  zk:
    servers: test01:2181
  canal:
    destination: i11
  kudu:
    masterAddresses: test02


spring:
  datasource:
    url: jdbc:mysql://hdp04:3306/canal_kudu_syncer
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver